import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Base/Navbar";
import SocIntro from '@/components/Base/SocIntro'
import EventsCard from "@/components/Base/EventsCard";
import Carousel from "@/components/Base/Carousels/Carousel";
import EventCarousel from "@/components/Base/Carousels/EventCarousel";
import FanArts from "@/components/Base/FanArts";
import AmvCarousel from "@/components/Base/Carousels/AmvCarousel";
import Footer from "@/components/Base/Footer";
import AboutUs from "@/components/Base/AboutUs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const events = [
    {
      key: 0,
      name: "Treasure Hunt",
      url: "/images/hunt.png",
      content: ["Lorem ipsum odor amet, consectetuer adipiscing elit. Dui volutpat torquent netus est augue. Commodo risus vel adipiscing, est convallis nostra. Class fringilla etiam dis tellus suscipit adipiscing fusce curabitur. Proin pellentesque nascetur consectetur convallis, varius quisque. Fermentum ac libero et maximus primis litora massa orci. Fames auctor maecenas .","Sagittis himenaeos magna parturient himenaeos dictumst ligula. Amet maximus per diam tempor, egestas ullamcorper. Etiam penatibus urna nulla praesent volutpat hac. Morbi"]
    },
    {
      key: 1,
      name: "OCAQ",
      url: "/images/hunt.png",
      content: ["Lorem ipsum odor amet, consectetuer adipiscing elit. Dui volutpat torquent netus est augue. Commodo risus vel adipiscing, est convallis nostra. Class fringilla etiam dis tellus suscipit adipiscing fusce curabitur. Proin pellentesque nascetur consectetur convallis, varius quisque. Fermentum ac libero et maximus primis litora massa orci. Fames auctor maecenas .","Sagittis himenaeos magna parturient himenaeos dictumst ligula. Amet maximus per diam tempor, egestas ullamcorper. Etiam penatibus urna nulla praesent volutpat hac. Morbi"]
    },
    {
      key: 2,
      name: "Art Competition",
      url: "/images/hunt.png",
      content: ["Lorem ipsum odor amet, consectetuer adipiscing elit. Dui volutpat torquent netus est augue. Commodo risus vel adipiscing, est convallis nostra. Class fringilla etiam dis tellus suscipit adipiscing fusce curabitur. Proin pellentesque nascetur consectetur convallis, varius quisque. Fermentum ac libero et maximus primis litora massa orci. Fames auctor maecenas .","Sagittis himenaeos magna parturient himenaeos dictumst ligula. Amet maximus per diam tempor, egestas ullamcorper. Etiam penatibus urna nulla praesent volutpat hac. Morbi"]
    }
  ]
  const amvs = [
    {
      key: 0,
      url: "/images/amv.png"
    }
  ]
  return (
    <>
      <Head>
        <title>Create Mask App</title>
        <meta name="description" content="Generated by create Mask app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Navbar />
          <SocIntro />
          <EventsCard />
          {/* <div className={styles.carousel}>
            <Carousel bottom={false}  data={events} Template={EventCarousel}>
            </Carousel>
          </div> */}
          <FanArts />
          <div className={styles.amvcarousel}>
            <Carousel bottom={true} data={amvs} Template={AmvCarousel} />
          </div>
          <AboutUs />
          <Footer />
        </main>
        </div>
    </>
  );
}
