import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Base/Navbar";
import SocIntro from '@/components/Base/SocIntro'
import EventsCard from "@/components/Base/EventsCard";
import Carousel from "@/components/Base/Carousels/Carousel";
import EventCarousel from "@/components/Base/Carousels/EventCarousel";
import FanArts from "@/components/Base/FanArts";
import AmvCarousel from "@/components/Base/Carousels/AmvCarousel";
import Footer from "@/components/Base/Footer";
import AboutUs from "@/components/Base/AboutUs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Mask App</title>
        <meta name="description" content="Generated by create Mask app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Navbar />
          <SocIntro />
          <EventsCard />
          <div className={styles.carousel}>
            <Carousel bottom={false}>
              <EventCarousel />
            </Carousel>
          </div>
          <FanArts />
          <div className={styles.amvcarousel}>
            <Carousel bottom={true}>
              <AmvCarousel />
            </Carousel>
          </div>
          <AboutUs />
          <Footer />
        </main>
        </div>
    </>
  );
}
